---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bff
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mobile-bff
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      containers:
      - name: mobile-bff
        image: mobile-bff:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mobile-bff-env
      terminationGracePeriodSeconds: 180